package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.46

import (
	"context"

	"github.com/parvesh12/go-graphqlapi/api"
	"github.com/parvesh12/go-graphqlapi/config"
	"github.com/parvesh12/go-graphqlapi/graph/model"
)

func dbset() *api.API {

	return &api.API{
		DB: config.SetupDB(),
	}
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, login model.Login) (*bool, error) {

	api := dbset()

	return api.LoginHandler(ctx, login)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
